//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace minas.teste.prototype.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TipoSensorSelecionado {
            get {
                return ((string)(this["TipoSensorSelecionado"]));
            }
            set {
                this["TipoSensorSelecionado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PortaCOMSelecionada {
            get {
                return ((string)(this["PortaCOMSelecionada"]));
            }
            set {
                this["PortaCOMSelecionada"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModuloSelecionado
        {
            get
            {
                return ((string)(this["ModuloSelecionado"]));
            }
            set
            {
                this["ModuloSelecionado"] = value;
            }
        }

        // Add this property to the Settings class in your application settings file
        [UserScopedSetting()]
        [DefaultSettingValue("{}")]
        public string CalibrationCoefficientsJSON
        {
            get { return (string)this["CalibrationCoefficientsJSON"]; }
            set { this["CalibrationCoefficientsJSON"] = value; }
        }



    }
}
